apiVersion: apps/v1
kind: Deployment
metadata:
  name: censor
  namespace: cloud
spec:
  replicas: 2
  selector:
    matchLabels:
      app: censor
  template:
    metadata:
      labels:
        app: censor
    spec:
      nodeSelector:
        layer: cloud
      containers:
      - name: censor
        image: dozzap/workflow_published-censor:latest
        ports:
        - containerPort: 5000
        env:
        - name: MQTT_BROKER
          value: "mosquitto-service.wavelength"
        - name: MQTT_TOPIC_SUB
          value: "pipeline/profanity/out"
        - name: MQTT_TOPIC_PUB
          value: "pipeline/censor/out"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: compression
  namespace: cloud
spec:
  replicas: 2
  selector:
    matchLabels:
      app: compression
  template:
    metadata:
      labels:
        app: compression
    spec:
      nodeSelector:
        layer: cloud
      containers:
      - name: compression
        image: dozzap/workflow_published-compression:latest
        ports:
        - containerPort: 5000
        env:
        - name: MQTT_BROKER
          value: "mosquitto-service.wavelength"
        - name: MQTT_TOPIC_SUB
          value: "pipeline/censor/out"
        - name: MQTT_TOPIC_PUB
          value: "pipeline/compression/out"

---
apiVersion: v1
kind: Service
metadata:
  name: censor-service
  namespace: cloud
spec:
  type: LoadBalancer
  ports:
  - port: 5004
    targetPort: 5000
  selector:
    app: censor

---
apiVersion: v1
kind: Service
metadata:
  name: compression-service
  namespace: cloud
spec:
  type: LoadBalancer
  ports:
  - port: 5005
    targetPort: 5000
  selector:
    app: compression

---
apiVersion: v1
kind: Service
metadata:
  name: mosquitto-lb
  namespace: cloud
spec:
  type: LoadBalancer
  selector:
    app: mosquitto
  ports:
    - protocol: TCP
      port: 1883
      targetPort: 1883
