

#!/bin/bash
sudo yum update -y
sudo yum install -y git
cd /home/ssm-user

# setup for workers
# ensure that the master node is communicating to the worker node by editting /etc/hosts and inputting the ip address and your desired name for those ip addresses
# sudo nano /etc/hosts

# installation of kubernetes 
sudo swapoff -a

# set ip bridge for communication

cat <<EOF | sudo tee /etc/modules-load.d/k8s.conf
overlay
br_netfilter
EOF

sudo modprobe overlay
sudo modprobe br_netfilter



cat <<EOF | sudo tee /etc/sysctl.d/k8s.conf
net.bridge.bridge-nf-call-iptables  = 1
net.bridge.bridge-nf-call-ip6tables = 1
net.ipv4.ip_forward                 = 1
EOF


# apply the changes
sudo sysctl --system

sudo tee /etc/yum.repos.d/kubernetes.repo <<EOF
[kubernetes]
name=Kubernetes
baseurl=https://pkgs.k8s.io/core:/stable:/v1.28/rpm/
enabled=1
gpgcheck=1
gpgkey=https://pkgs.k8s.io/core:/stable:/v1.28/rpm/repodata/repomd.xml.key
repo_gpgcheck=1
EOF

#  Install Kubernetes components
echo "Installing Kubernetes components..."
sudo apt install -y kubelet=1.28-00 kubeadm=1.28-00 kubectl=1.28-00 --disableexcludes=kubernetes

# this makes sure that current and future applications will be using the same version 
sudo apt-mark hold kubelet kubeadm kubectl


# Download Docker Compose
sudo yum install docker containerd screen -y
# sleep 1
# wget https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)
sleep 1
sudo mv docker-compose-$(uname -s)-$(uname -m) /usr/libexec/docker/cli-plugins/docker-compose
sleep 1
chmod +x /usr/libexec/docker/cli-plugins/docker-compose
sleep 5
systemctl enable docker.service --now
sudo usermod -a -G docker ec2-user
sudo usermod -a -G docker ssm-user


# create a default config file for docker, that will be used for all nodes
sudo sh -c "containerd config default > /etc/containerd/config.toml"

# this command ensures that kubernetes efficienctly manage system resources for containers
sudo sed -i 's/ SystemdCgroup = false/ SystemdCgroup = true/' /etc/containerd/config.toml

# restarts kubelet service
sudo systemctl restart containerd.service && sudo systemctl restart kubelet.servic

sudo systemctl enable kubelet.service

# download essential components for cluster management and orchestration
sudo kubeadm config images pull

#to connect to a cluster, run the command below with the token generated by the master
# kubeadm join <kubernetes token>

# once the connection between the master node and the worker node has been establish, see if given a container node created by the master is being sent to the worker nodes
sudo docker ps | grep nginx


sudo mkdir -p /mosquitto/config
sudo mkdir -p /mosquitto/data
sudo mkdir -p /mosquitto/log

sudo bash -c 'cat > /mosquitto/config/mosquitto.conf <<EOF
persistence true
persistence_location /mosquitto/data/
log_dest file /mosquitto/log/mosquitto.log
allow_anonymous true
listener 1883
EOF'

docker run -d -p 1883:1883 -p 9001:9001 -v /mosquitto:/mosquitto eclipse-mosquitto